In [1]:
# What is Pandas?

# Pandas is an open-source Python library used for:

# Data manipulation

# Data cleaning

# Data analysis

# Data transformation

# Working with structured data (tables)

# It was created by Wes McKinney in 2008.

# It is built on top of:

# NumPy

# Python

# 🎯 Why Pandas is Important in Data Science

# In real-world data science:

# 70–80% time → Data cleaning

# 10–20% time → Modeling

# Pandas is mainly used in:

# Data preprocessing

# EDA (Exploratory Data Analysis)

# Feature engineering

# Preparing data for ML models

In [2]:
print("Working or not")

Working or not

In [ ]:
import pandas as pd

In [4]:
# list 
data1=[1,2,3,4,5]
pd.DataFrame(data1)

   0
0  1
1  2
2  3
3  4
4  5

In [5]:
data11=pd.DataFrame(data1)
print(data11)
type(data11)

   0
0  1
1  2
2  3
3  4
4  5

pandas.DataFrame

In [6]:
data2=[["shan",23],["rihan",43]]
data22=pd.DataFrame(data2)
print(data22)

       0   1
0   shan  23
1  rihan  43

In [7]:
data22=pd.DataFrame(data2,columns=["name","age"])
print(data22)

    name  age
0   shan   23
1  rihan   43

In [8]:
data22=pd.DataFrame(data2,columns=("name","age"),index=[1,2])
print(data22)

    name  age
1   shan   23
2  rihan   43

In [9]:
# .

In [10]:
# use dictonery
data1={"name":["shan","rihan"],"age":[12,14]}

In [11]:
pd.DataFrame(data1)

    name  age
0   shan   12
1  rihan   14

In [12]:
newdata1=pd.DataFrame(data1)
print(newdata1)

    name  age
0   shan   12
1  rihan   14

In [13]:
# .

In [14]:
data2=[{"shan":12,"rihan":23},{"shan":23,"rihan":233,"faiz":90}]
data3=pd.DataFrame(data2)

In [15]:

data3["shan"].dtype
data3["shan"]

0    12
1    23
Name: shan, dtype: int64

In [16]:
# .

In [18]:
pd.read_csv("/home/choudhary/Desktop/LEARN with  GIT /DataScience-And-AI-Learning/1 Data analysis using pandas/csvdata1.csv")

            Name   class  gender  age
0  mohammad shan        2      m   23
1           rihan       3      m   44
2             nia       3      f   32
3             mir       2      f   23

In [28]:
pd.read_excel("/home/choudhary/Desktop/LEARN with  GIT /DataScience-And-AI-Learning/1 Data analysis using pandas/xldata1.xlsx")

            Name   class  gender  age
0  mohammad shan        2      m   23
1           rihan       3      m   44
2             nia       3      f   32
3             mir       2      f   23

In [30]:
pd.read_csv("/home/choudhary/Desktop/LEARN with  GIT /DataScience-And-AI-Learning/1 Data analysis using pandas/text.txt",sep="@")

            Name   class  gender  age
0  mohammad shan        2      m   23
1            riha       3      m   44
2              ni       3      f   32
3             mir       2      f   23

In [ ]:
# .

In [40]:
data0 = {"name": ["rihan", "shan"], "age": 23}
print(type(data0))   # dict


df = pd.DataFrame(data0)
print(df)

<class 'dict'>
    name  age
0  rihan   23
1   shan   23

In [49]:
import json

json_text = '{"name": ["rihan", "shan"], "age": 23}'
d = json.loads(json_text)

print(d)
print(type(d))   # dict

{'name': ['rihan', 'shan'], 'age': 23}
<class 'dict'>

In [ ]:
import json

json_text = '{"name": ["rihan", "shan"], "age": 23}'
d = json.loads(json_text)

print(d)
print(type(d))   # dict

In [ ]:
# .

In [50]:
pd.read_csv("https://raw.githubusercontent.com/MohdShanChoudhary/DataScience-And-AI-Learning/refs/heads/main/1%20Data%20analysis%20using%20pandas/googleplaystore.csv")

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [60]:
shan=pd.read_csv("/home/choudhary/Desktop/LEARN with  GIT /DataScience-And-AI-Learning/1 Data analysis using pandas/csvdata1.csv")
print(shan)
print(shan.shape)
print("and")
print(shan.dtypes)

            Name   class  gender  age
0  mohammad shan        2      m   23
1           rihan       3      m   44
2             nia       3      f   32
3             mir       2      f   23
(4, 4)
and
Name        str
class     int64
gender      str
age       int64
dtype: object

In [69]:
shan.head(2)

            Name   class  gender  age
0  mohammad shan        2      m   23
1           rihan       3      m   44

In [70]:
shan.tail(20)
# only  ending 5 rows will come

            Name   class  gender  age
0  mohammad shan        2      m   23
1           rihan       3      m   44
2             nia       3      f   32
3             mir       2      f   23

In [76]:
# for rendom sempal
shan.sample(4)

            Name   class  gender  age
2             nia       3      f   32
1           rihan       3      m   44
3             mir       2      f   23
0  mohammad shan        2      m   23

In [79]:
shan.values

array([['mohammad shan ', 2, 'm', 23],
       ['rihan', 3, 'm', 44],
       ['nia', 3, 'f', 32],
       ['mir', 2, 'f', 23]], dtype=object)

In [80]:
shan.size

16

In [81]:
shan.ndim

2

In [83]:
shan.axes

[RangeIndex(start=0, stop=4, step=1),
 Index(['Name ', 'class ', 'gender', 'age'], dtype='str')]

In [ ]:
shan.T
# transfrom

                     0      1    2    3
Name    mohammad shan   rihan  nia  mir
class                2      3    3    2
gender               m      m    f    f
age                 23     44   32   23

In [86]:
shan.empty

False

In [88]:
data={1,2,3,4,5}
n=pd.DataFrame(data)
print(n)
n.apply(lambda x:x+10)

   0
0  1
1  2
2  3
3  4
4  5

    0
0  11
1  12
2  13
3  14
4  15

In [89]:
import numpy as np
n.apply(np.mean)

0    3.0
dtype: float64

In [ ]:
n.reindex(index=["shan"])
# and rename is use for cloumn 
# df = df.rename(columns={
#     "name": "Name",
#     "age": "Age"
# })

       0
shan NaN

In [ ]:
# df.columns = ["Name", "Age"]   to change the name  of columns
# df.index = ["row1", "row2"]

In [1]:
print("test")

test

In [8]:
import pandas as pd 
df = pd.DataFrame({
    "A": [10, 20, 30],
    "B": [40, 50, 60]
}, index=["x", "y", "z"])

df.reindex(["z", "x", "y"])
print(df)

    A   B
x  10  40
y  20  50
z  30  60

In [ ]:
df = pd.DataFrame({
    "A": [10, 20, 30],
    "B": [40, 50, 60]
}, index=["x", "y", "z"])

df.reindex(["z", "x", "k","y"])

      A     B
z  30.0  60.0
x  10.0  40.0
k   NaN   NaN
y  20.0  50.0

In [7]:
df.reindex(["z", "x", "k","y"],fill_value="this is nan value ")

                    A                   B
z                  30                  60
x                  10                  40
k  this is nan value   this is nan value
y                  20                  50