In [80]:
import pandas as pd

In [81]:
print("test")

test

In [82]:
df = pd.DataFrame({
    "A": [10, 20, 30],
    "B": [40, 50, 60]
}, index=["x", "y", "z"])

print(df.columns)
df.sort_index()
df.sort_values(by="A")   # here a  mean assanding

Index(['A', 'B'], dtype='str')

    A   B
x  10  40
y  20  50
z  30  60

In [83]:
d1=pd.read_csv("/home/choudhary/Desktop/LEARN with  GIT /DataScience-And-AI-Learning/1 Data analysis using pandas/d1.csv")

In [84]:
# print(d1)
d1.head()
d1.tail(3)

,student_id,name,gender,age,city,course,semester,math_score,stats_score,cs_score,attendance_pct,internship
17,18,Tanya,F,20,Mumbai,Data Science,1,83,85,80,89,Yes
18,19,Dev,M,22,Indore,Web Dev,3,69,71,68,78,No
19,20,Isha,F,21,Surat,AI,2,88,86,90,91,Yes

In [85]:
d1.head()

,student_id,name,gender,age,city,course,semester,math_score,stats_score,cs_score,attendance_pct,internship
0,1,Ayaan,M,20,Delhi,Data Science,1,78,82,75,92,Yes
1,2,Riya,F,21,Mumbai,AI,2,88,91,89,85,No
2,3,Arjun,M,22,Pune,Data Science,3,65,70,72,76,No
3,4,Neha,F,20,Delhi,Web Dev,1,90,85,88,95,Yes
4,5,Karan,M,23,Bangalore,AI,4,55,60,58,68,No

In [86]:
d1.reindex([1,2,3,4,5])

,student_id,name,gender,age,city,course,semester,math_score,stats_score,cs_score,attendance_pct,internship
1,2,Riya,F,21,Mumbai,AI,2,88,91,89,85,No
2,3,Arjun,M,22,Pune,Data Science,3,65,70,72,76,No
3,4,Neha,F,20,Delhi,Web Dev,1,90,85,88,95,Yes
4,5,Karan,M,23,Bangalore,AI,4,55,60,58,68,No
5,6,Priya,F,22,Chennai,Data Science,3,72,75,70,80,Yes

In [87]:
d1.head()

,student_id,name,gender,age,city,course,semester,math_score,stats_score,cs_score,attendance_pct,internship
0,1,Ayaan,M,20,Delhi,Data Science,1,78,82,75,92,Yes
1,2,Riya,F,21,Mumbai,AI,2,88,91,89,85,No
2,3,Arjun,M,22,Pune,Data Science,3,65,70,72,76,No
3,4,Neha,F,20,Delhi,Web Dev,1,90,85,88,95,Yes
4,5,Karan,M,23,Bangalore,AI,4,55,60,58,68,No

In [88]:
d1.sort_index()

,student_id,name,gender,age,city,course,semester,math_score,stats_score,cs_score,attendance_pct,internship
0,1,Ayaan,M,20,Delhi,Data Science,1,78,82,75,92,Yes
1,2,Riya,F,21,Mumbai,AI,2,88,91,89,85,No
2,3,Arjun,M,22,Pune,Data Science,3,65,70,72,76,No
3,4,Neha,F,20,Delhi,Web Dev,1,90,85,88,95,Yes
4,5,Karan,M,23,Bangalore,AI,4,55,60,58,68,No
5,6,Priya,F,22,Chennai,Data Science,3,72,75,70,80,Yes
6,7,Rohit,M,21,Kolkata,Web Dev,2,81,79,83,88,Yes
7,8,Simran,F,20,Jaipur,AI,1,95,93,97,98,Yes
8,9,Aditya,M,24,Hyderabad,Data Science,4,60,65,62,70,No
9,10,Pooja,F,21,Delhi,Web Dev,2,85,80,78,90,Yes
10,11,Aman,M,22,Mumbai,AI,3,70,68,74,82,No
11,12,Kriti,F,23,Pune,Data Science,4,92,89,90,96,Yes
12,13,Sahil,M,20,Chandigarh,Web Dev,1,66,64,69,75,No
13,14,Nisha,F,22,Bangalore,AI,3,74,77,73,84,Yes
14,15,Vikas,M,21,Jaipur,Data Science,2,80,78,82,86,Yes
15,16,Meera,F,24,Chennai,Web Dev,4,58,62,60,65,No
16,17,Rahul,M,23,Delhi,AI,4,90,92,91,94,Yes
17,18,Tanya,F,20,Mumbai,Data Science,1,83,85,80,89,Yes
18,19,Dev,M,22,Indore,Web Dev,3,69,71,68,78,No
19,20,Isha,F,21,Surat,AI,2,88,86,90,91,Yes

In [89]:
d1.sort_values(by="age")

,student_id,name,gender,age,city,course,semester,math_score,stats_score,cs_score,attendance_pct,internship
0,1,Ayaan,M,20,Delhi,Data Science,1,78,82,75,92,Yes
3,4,Neha,F,20,Delhi,Web Dev,1,90,85,88,95,Yes
7,8,Simran,F,20,Jaipur,AI,1,95,93,97,98,Yes
12,13,Sahil,M,20,Chandigarh,Web Dev,1,66,64,69,75,No
17,18,Tanya,F,20,Mumbai,Data Science,1,83,85,80,89,Yes
6,7,Rohit,M,21,Kolkata,Web Dev,2,81,79,83,88,Yes
9,10,Pooja,F,21,Delhi,Web Dev,2,85,80,78,90,Yes
14,15,Vikas,M,21,Jaipur,Data Science,2,80,78,82,86,Yes
19,20,Isha,F,21,Surat,AI,2,88,86,90,91,Yes
1,2,Riya,F,21,Mumbai,AI,2,88,91,89,85,No
13,14,Nisha,F,22,Bangalore,AI,3,74,77,73,84,Yes
5,6,Priya,F,22,Chennai,Data Science,3,72,75,70,80,Yes
2,3,Arjun,M,22,Pune,Data Science,3,65,70,72,76,No
18,19,Dev,M,22,Indore,Web Dev,3,69,71,68,78,No
10,11,Aman,M,22,Mumbai,AI,3,70,68,74,82,No
4,5,Karan,M,23,Bangalore,AI,4,55,60,58,68,No
11,12,Kriti,F,23,Pune,Data Science,4,92,89,90,96,Yes
16,17,Rahul,M,23,Delhi,AI,4,90,92,91,94,Yes
15,16,Meera,F,24,Chennai,Web Dev,4,58,62,60,65,No
8,9,Aditya,M,24,Hyderabad,Data Science,4,60,65,62,70,No

In [90]:
# d1.loc[r,c]

#d1.loc["0","name"]   # galat 
d1.loc[0:5, "name"]  # sahi
d1.loc[0:, "name"]  # sahi

0      Ayaan
1       Riya
2      Arjun
3       Neha
4      Karan
5      Priya
6      Rohit
7     Simran
8     Aditya
9      Pooja
10      Aman
11     Kriti
12     Sahil
13     Nisha
14     Vikas
15     Meera
16     Rahul
17     Tanya
18       Dev
19      Isha
Name: name, dtype: str

In [91]:

d1.loc[0:, "name":"internship"]  # sahi

,name,gender,age,city,course,semester,math_score,stats_score,cs_score,attendance_pct,internship
0,Ayaan,M,20,Delhi,Data Science,1,78,82,75,92,Yes
1,Riya,F,21,Mumbai,AI,2,88,91,89,85,No
2,Arjun,M,22,Pune,Data Science,3,65,70,72,76,No
3,Neha,F,20,Delhi,Web Dev,1,90,85,88,95,Yes
4,Karan,M,23,Bangalore,AI,4,55,60,58,68,No
5,Priya,F,22,Chennai,Data Science,3,72,75,70,80,Yes
6,Rohit,M,21,Kolkata,Web Dev,2,81,79,83,88,Yes
7,Simran,F,20,Jaipur,AI,1,95,93,97,98,Yes
8,Aditya,M,24,Hyderabad,Data Science,4,60,65,62,70,No
9,Pooja,F,21,Delhi,Web Dev,2,85,80,78,90,Yes
10,Aman,M,22,Mumbai,AI,3,70,68,74,82,No
11,Kriti,F,23,Pune,Data Science,4,92,89,90,96,Yes
12,Sahil,M,20,Chandigarh,Web Dev,1,66,64,69,75,No
13,Nisha,F,22,Bangalore,AI,3,74,77,73,84,Yes
14,Vikas,M,21,Jaipur,Data Science,2,80,78,82,86,Yes
15,Meera,F,24,Chennai,Web Dev,4,58,62,60,65,No
16,Rahul,M,23,Delhi,AI,4,90,92,91,94,Yes
17,Tanya,F,20,Mumbai,Data Science,1,83,85,80,89,Yes
18,Dev,M,22,Indore,Web Dev,3,69,71,68,78,No
19,Isha,F,21,Surat,AI,2,88,86,90,91,Yes

In [92]:

d1.loc[0, "name"]

'Ayaan'

In [93]:

d1.loc[0,"name"]

'Ayaan'

In [94]:
d1.loc[0,"name"]

'Ayaan'

In [95]:
d1.loc[0:5, ["name","internship"]]  # sahi

    name internship
0  Ayaan        Yes
1   Riya         No
2  Arjun         No
3   Neha        Yes
4  Karan         No
5  Priya        Yes

In [96]:
d1["age"]<24

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8     False
9      True
10     True
11     True
12     True
13     True
14     True
15    False
16     True
17     True
18     True
19     True
Name: age, dtype: bool

*** .iloc -> is  use  for  integer location

In [97]:
d1.iloc[1:5,]

,student_id,name,gender,age,city,course,semester,math_score,stats_score,cs_score,attendance_pct,internship
1,2,Riya,F,21,Mumbai,AI,2,88,91,89,85,No
2,3,Arjun,M,22,Pune,Data Science,3,65,70,72,76,No
3,4,Neha,F,20,Delhi,Web Dev,1,90,85,88,95,Yes
4,5,Karan,M,23,Bangalore,AI,4,55,60,58,68,No

In [98]:
d1.iloc[1,1]

'Riya'

In [99]:
d1.iloc[1:5,0]

1    2
2    3
3    4
4    5
Name: student_id, dtype: int64

concanitaion of 2 data frame

In [100]:
d2=pd.read_csv("/home/choudhary/Desktop/LEARN with  GIT /DataScience-And-AI-Learning/1 Data analysis using pandas/d2.csv")

In [101]:
d2.head()

,student_id,name,gender,age,city,course,semester,math_score,stats_score,cs_score,attendance_pct,internship
0,21,Farhan,M,22,Lucknow,AI,2,76,79,74,83,No
1,22,Sneha,F,21,Noida,Data Science,1,84,88,86,90,Yes
2,23,Imran,M,23,Bhopal,Web Dev,3,62,65,60,72,No
3,24,Kavya,F,20,Dehradun,AI,1,91,94,89,97,Yes
4,25,Ankit,M,24,Gurgaon,Data Science,4,68,70,66,74,No

In [102]:
pd.concat([d1,d2])  # it will concat in verticaly

,student_id,name,gender,age,city,course,semester,math_score,stats_score,cs_score,attendance_pct,internship
0,1,Ayaan,M,20,Delhi,Data Science,1,78,82,75,92,Yes
1,2,Riya,F,21,Mumbai,AI,2,88,91,89,85,No
2,3,Arjun,M,22,Pune,Data Science,3,65,70,72,76,No
3,4,Neha,F,20,Delhi,Web Dev,1,90,85,88,95,Yes
4,5,Karan,M,23,Bangalore,AI,4,55,60,58,68,No
5,6,Priya,F,22,Chennai,Data Science,3,72,75,70,80,Yes
6,7,Rohit,M,21,Kolkata,Web Dev,2,81,79,83,88,Yes
7,8,Simran,F,20,Jaipur,AI,1,95,93,97,98,Yes
8,9,Aditya,M,24,Hyderabad,Data Science,4,60,65,62,70,No
9,10,Pooja,F,21,Delhi,Web Dev,2,85,80,78,90,Yes
10,11,Aman,M,22,Mumbai,AI,3,70,68,74,82,No
11,12,Kriti,F,23,Pune,Data Science,4,92,89,90,96,Yes
12,13,Sahil,M,20,Chandigarh,Web Dev,1,66,64,69,75,No
13,14,Nisha,F,22,Bangalore,AI,3,74,77,73,84,Yes
14,15,Vikas,M,21,Jaipur,Data Science,2,80,78,82,86,Yes
15,16,Meera,F,24,Chennai,Web Dev,4,58,62,60,65,No
16,17,Rahul,M,23,Delhi,AI,4,90,92,91,94,Yes
17,18,Tanya,F,20,Mumbai,Data Science,1,83,85,80,89,Yes
18,19,Dev,M,22,Indore,Web Dev,3,69,71,68,78,No
19,20,Isha,F,21,Surat,AI,2,88,86,90,91,Yes
0,21,Farhan,M,22,Lucknow,AI,2,76,79,74,83,No
1,22,Sneha,F,21,Noida,Data Science,1,84,88,86,90,Yes
2,23,Imran,M,23,Bhopal,Web Dev,3,62,65,60,72,No
3,24,Kavya,F,20,Dehradun,AI,1,91,94,89,97,Yes
4,25,Ankit,M,24,Gurgaon,Data Science,4,68,70,66,74,No
5,26,Ritu,F,22,Patna,Web Dev,2,79,77,81,85,Yes
6,27,Manish,M,21,Ranchi,AI,2,73,75,72,80,No
7,28,Pallavi,F,23,Udaipur,Data Science,3,88,86,90,92,Yes
8,29,Deepak,M,20,Meerut,Web Dev,1,64,61,67,70,No
9,30,Shreya,F,22,Agra,AI,3,90,89,92,95,Yes

In [103]:
pd.concat([d1,d2],keys=["data 1","data 2"])

           student_id     name gender  age        city        course  \
data 1 0            1    Ayaan      M   20       Delhi  Data Science
       1            2     Riya      F   21      Mumbai            AI
       2            3    Arjun      M   22        Pune  Data Science
       3            4     Neha      F   20       Delhi       Web Dev
       4            5    Karan      M   23   Bangalore            AI
       5            6    Priya      F   22     Chennai  Data Science
       6            7    Rohit      M   21     Kolkata       Web Dev
       7            8   Simran      F   20      Jaipur            AI
       8            9   Aditya      M   24   Hyderabad  Data Science
       9           10    Pooja      F   21       Delhi       Web Dev
       10          11     Aman      M   22      Mumbai            AI
       11          12    Kriti      F   23        Pune  Data Science
       12          13    Sahil      M   20  Chandigarh       Web Dev
       13          14    Nisha      F   22   Bangalore            AI
       14          15    Vikas      M   21      Jaipur  Data Science
       15          16    Meera      F   24     Chennai       Web Dev
       16          17    Rahul      M   23       Delhi            AI
       17          18    Tanya      F   20      Mumbai  Data Science
       18          19      Dev      M   22      Indore       Web Dev
       19          20     Isha      F   21       Surat            AI
data 2 0           21   Farhan      M   22     Lucknow            AI
       1           22    Sneha      F   21       Noida  Data Science
       2           23    Imran      M   23      Bhopal       Web Dev
       3           24    Kavya      F   20    Dehradun            AI
       4           25    Ankit      M   24     Gurgaon  Data Science
       5           26     Ritu      F   22       Patna       Web Dev
       6           27   Manish      M   21      Ranchi            AI
       7           28  Pallavi      F   23     Udaipur  Data Science
       8           29   Deepak      M   20      Meerut       Web Dev
       9           30   Shreya      F   22        Agra            AI

           semester  math_score  stats_score  cs_score  attendance_pct  \
data 1 0          1          78           82        75              92
       1          2          88           91        89              85
       2          3          65           70        72              76
       3          1          90           85        88              95
       4          4          55           60        58              68
       5          3          72           75        70              80
       6          2          81           79        83              88
       7          1          95           93        97              98
       8          4          60           65        62              70
       9          2          85           80        78              90
       10         3          70           68        74              82
       11         4          92           89        90              96
       12         1          66           64        69              75
       13         3          74           77        73              84
       14         2          80           78        82              86
       15         4          58           62        60              65
       16         4          90           92        91              94
       17         1          83           85        80              89
       18         3          69           71        68              78
       19         2          88           86        90              91
data 2 0          2          76           79        74              83
       1          1          84           88        86              90
       2          3          62           65        60              72
       3          1          91           94        89              97
       4          4          68           70        66              74
       5          2          79           77        81              85
       6          2          73           75        72              80
       7          3          88           86        90              92
       8          1          64           61        67              70
       9          3          90           89        92              95

          internship
data 1 0         Yes
       1          No
       2          No
       3         Yes
       4          No
       5         Yes
       6         Yes
       7         Yes
       8          No
       9         Yes
       10         No
       11        Yes
       12         No
       13        Yes
       14        Yes
       15         No
       16        Yes
       17        Yes
       18         No
       19        Yes
data 2 0          No
       1         Yes
       2          No
       3         Yes
       4          No
       5         Yes
       6          No
       7         Yes
       8          No
       9         Yes

In [104]:
pd.concat([d1,d2],ignore_index=True)

,student_id,name,gender,age,city,course,semester,math_score,stats_score,cs_score,attendance_pct,internship
0,1,Ayaan,M,20,Delhi,Data Science,1,78,82,75,92,Yes
1,2,Riya,F,21,Mumbai,AI,2,88,91,89,85,No
2,3,Arjun,M,22,Pune,Data Science,3,65,70,72,76,No
3,4,Neha,F,20,Delhi,Web Dev,1,90,85,88,95,Yes
4,5,Karan,M,23,Bangalore,AI,4,55,60,58,68,No
5,6,Priya,F,22,Chennai,Data Science,3,72,75,70,80,Yes
6,7,Rohit,M,21,Kolkata,Web Dev,2,81,79,83,88,Yes
7,8,Simran,F,20,Jaipur,AI,1,95,93,97,98,Yes
8,9,Aditya,M,24,Hyderabad,Data Science,4,60,65,62,70,No
9,10,Pooja,F,21,Delhi,Web Dev,2,85,80,78,90,Yes
10,11,Aman,M,22,Mumbai,AI,3,70,68,74,82,No
11,12,Kriti,F,23,Pune,Data Science,4,92,89,90,96,Yes
12,13,Sahil,M,20,Chandigarh,Web Dev,1,66,64,69,75,No
13,14,Nisha,F,22,Bangalore,AI,3,74,77,73,84,Yes
14,15,Vikas,M,21,Jaipur,Data Science,2,80,78,82,86,Yes
15,16,Meera,F,24,Chennai,Web Dev,4,58,62,60,65,No
16,17,Rahul,M,23,Delhi,AI,4,90,92,91,94,Yes
17,18,Tanya,F,20,Mumbai,Data Science,1,83,85,80,89,Yes
18,19,Dev,M,22,Indore,Web Dev,3,69,71,68,78,No
19,20,Isha,F,21,Surat,AI,2,88,86,90,91,Yes
20,21,Farhan,M,22,Lucknow,AI,2,76,79,74,83,No
21,22,Sneha,F,21,Noida,Data Science,1,84,88,86,90,Yes
22,23,Imran,M,23,Bhopal,Web Dev,3,62,65,60,72,No
23,24,Kavya,F,20,Dehradun,AI,1,91,94,89,97,Yes
24,25,Ankit,M,24,Gurgaon,Data Science,4,68,70,66,74,No
25,26,Ritu,F,22,Patna,Web Dev,2,79,77,81,85,Yes
26,27,Manish,M,21,Ranchi,AI,2,73,75,72,80,No
27,28,Pallavi,F,23,Udaipur,Data Science,3,88,86,90,92,Yes
28,29,Deepak,M,20,Meerut,Web Dev,1,64,61,67,70,No
29,30,Shreya,F,22,Agra,AI,3,90,89,92,95,Yes

In [105]:
pd.concat([d1,d2],keys=["data 1","data 2"],axis=1)

       data 1                                                        \
   student_id    name gender age        city        course semester
0           1   Ayaan      M  20       Delhi  Data Science        1
1           2    Riya      F  21      Mumbai            AI        2
2           3   Arjun      M  22        Pune  Data Science        3
3           4    Neha      F  20       Delhi       Web Dev        1
4           5   Karan      M  23   Bangalore            AI        4
5           6   Priya      F  22     Chennai  Data Science        3
6           7   Rohit      M  21     Kolkata       Web Dev        2
7           8  Simran      F  20      Jaipur            AI        1
8           9  Aditya      M  24   Hyderabad  Data Science        4
9          10   Pooja      F  21       Delhi       Web Dev        2
10         11    Aman      M  22      Mumbai            AI        3
11         12   Kriti      F  23        Pune  Data Science        4
12         13   Sahil      M  20  Chandigarh       Web Dev        1
13         14   Nisha      F  22   Bangalore            AI        3
14         15   Vikas      M  21      Jaipur  Data Science        2
15         16   Meera      F  24     Chennai       Web Dev        4
16         17   Rahul      M  23       Delhi            AI        4
17         18   Tanya      F  20      Mumbai  Data Science        1
18         19     Dev      M  22      Indore       Web Dev        3
19         20    Isha      F  21       Surat            AI        2

                                    ... data 2                                \
   math_score stats_score cs_score  ... gender   age      city        course
0          78          82       75  ...      M  22.0   Lucknow            AI
1          88          91       89  ...      F  21.0     Noida  Data Science
2          65          70       72  ...      M  23.0    Bhopal       Web Dev
3          90          85       88  ...      F  20.0  Dehradun            AI
4          55          60       58  ...      M  24.0   Gurgaon  Data Science
5          72          75       70  ...      F  22.0     Patna       Web Dev
6          81          79       83  ...      M  21.0    Ranchi            AI
7          95          93       97  ...      F  23.0   Udaipur  Data Science
8          60          65       62  ...      M  20.0    Meerut       Web Dev
9          85          80       78  ...      F  22.0      Agra            AI
10         70          68       74  ...    NaN   NaN       NaN           NaN
11         92          89       90  ...    NaN   NaN       NaN           NaN
12         66          64       69  ...    NaN   NaN       NaN           NaN
13         74          77       73  ...    NaN   NaN       NaN           NaN
14         80          78       82  ...    NaN   NaN       NaN           NaN
15         58          62       60  ...    NaN   NaN       NaN           NaN
16         90          92       91  ...    NaN   NaN       NaN           NaN
17         83          85       80  ...    NaN   NaN       NaN           NaN
18         69          71       68  ...    NaN   NaN       NaN           NaN
19         88          86       90  ...    NaN   NaN       NaN           NaN


   semester math_score stats_score cs_score attendance_pct internship
0       2.0       76.0        79.0     74.0           83.0         No
1       1.0       84.0        88.0     86.0           90.0        Yes
2       3.0       62.0        65.0     60.0           72.0         No
3       1.0       91.0        94.0     89.0           97.0        Yes
4       4.0       68.0        70.0     66.0           74.0         No
5       2.0       79.0        77.0     81.0           85.0        Yes
6       2.0       73.0        75.0     72.0           80.0         No
7       3.0       88.0        86.0     90.0           92.0        Yes
8       1.0       64.0        61.0     67.0           70.0         No
9       3.0       90.0        89.0     92.0           95.0        Yes
10      NaN        NaN         NaN      NaN            NaN        NaN
11      NaN        NaN         NaN      NaN            NaN        NaN
12      NaN        NaN         NaN      NaN            NaN        NaN
13      NaN        NaN         NaN      NaN            NaN        NaN
14      NaN        NaN         NaN      NaN            NaN        NaN
15      NaN        NaN         NaN      NaN            NaN        NaN
16      NaN        NaN         NaN      NaN            NaN        NaN
17      NaN        NaN         NaN      NaN            NaN        NaN
18      NaN        NaN         NaN      NaN            NaN        NaN
19      NaN        NaN         NaN      NaN            NaN        NaN

[20 rows x 24 columns]

In [106]:
pd.concat([d1,d2],axis=1)

,student_id,name,gender,age,city,course,semester,math_score,stats_score,cs_score,...,gender,age,city,course,semester,math_score,stats_score,cs_score,attendance_pct,internship
0,1,Ayaan,M,20,Delhi,Data Science,1,78,82,75,...,M,22.0,Lucknow,AI,2.0,76.0,79.0,74.0,83.0,No
1,2,Riya,F,21,Mumbai,AI,2,88,91,89,...,F,21.0,Noida,Data Science,1.0,84.0,88.0,86.0,90.0,Yes
2,3,Arjun,M,22,Pune,Data Science,3,65,70,72,...,M,23.0,Bhopal,Web Dev,3.0,62.0,65.0,60.0,72.0,No
3,4,Neha,F,20,Delhi,Web Dev,1,90,85,88,...,F,20.0,Dehradun,AI,1.0,91.0,94.0,89.0,97.0,Yes
4,5,Karan,M,23,Bangalore,AI,4,55,60,58,...,M,24.0,Gurgaon,Data Science,4.0,68.0,70.0,66.0,74.0,No
5,6,Priya,F,22,Chennai,Data Science,3,72,75,70,...,F,22.0,Patna,Web Dev,2.0,79.0,77.0,81.0,85.0,Yes
6,7,Rohit,M,21,Kolkata,Web Dev,2,81,79,83,...,M,21.0,Ranchi,AI,2.0,73.0,75.0,72.0,80.0,No
7,8,Simran,F,20,Jaipur,AI,1,95,93,97,...,F,23.0,Udaipur,Data Science,3.0,88.0,86.0,90.0,92.0,Yes
8,9,Aditya,M,24,Hyderabad,Data Science,4,60,65,62,...,M,20.0,Meerut,Web Dev,1.0,64.0,61.0,67.0,70.0,No
9,10,Pooja,F,21,Delhi,Web Dev,2,85,80,78,...,F,22.0,Agra,AI,3.0,90.0,89.0,92.0,95.0,Yes
10,11,Aman,M,22,Mumbai,AI,3,70,68,74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,Kriti,F,23,Pune,Data Science,4,92,89,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,Sahil,M,20,Chandigarh,Web Dev,1,66,64,69,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,Nisha,F,22,Bangalore,AI,3,74,77,73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,Vikas,M,21,Jaipur,Data Science,2,80,78,82,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,Meera,F,24,Chennai,Web Dev,4,58,62,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,Rahul,M,23,Delhi,AI,4,90,92,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,Tanya,F,20,Mumbai,Data Science,1,83,85,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,Dev,M,22,Indore,Web Dev,3,69,71,68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,Isha,F,21,Surat,AI,2,88,86,90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# group by

In [107]:

data = pd.DataFrame({
    "emp_id": [1, 2, 3, 4, 5, 6, 7],
    "name": ["Ali", "Rahul", "Neha", "Sara", "John", "Aman", "Priya"],
    "department": ["AI", "AI", "Data Science", "HR", "AI", "HR", "Data Science"],
    "salary": [50000, 60000, 55000, 65000, 58000, 62000, 54000],
    "experience": [2, 3, 2, 5, 1, 4, 3]
})

print(data)

   emp_id   name    department  salary  experience
0       1    Ali            AI   50000           2
1       2  Rahul            AI   60000           3
2       3   Neha  Data Science   55000           2
3       4   Sara            HR   65000           5
4       5   John            AI   58000           1
5       6   Aman            HR   62000           4
6       7  Priya  Data Science   54000           3

In [108]:
ok=data.groupby("department").groups

In [109]:
okk=data.groupby("department")

In [110]:
for i in ok:
    print(i)

AI
Data Science
HR

In [111]:
for i  in okk:
    print(i)

('AI',    emp_id   name department  salary  experience
0       1    Ali         AI   50000           2
1       2  Rahul         AI   60000           3
4       5   John         AI   58000           1)
('Data Science',    emp_id   name    department  salary  experience
2       3   Neha  Data Science   55000           2
6       7  Priya  Data Science   54000           3)
('HR',    emp_id  name department  salary  experience
3       4  Sara         HR   65000           5
5       6  Aman         HR   62000           4)

In [112]:
data.groupby("department").get_group("AI")

   emp_id   name department  salary  experience
0       1    Ali         AI   50000           2
1       2  Rahul         AI   60000           3
4       5   John         AI   58000           1

In [113]:
print(data)

   emp_id   name    department  salary  experience
0       1    Ali            AI   50000           2
1       2  Rahul            AI   60000           3
2       3   Neha  Data Science   55000           2
3       4   Sara            HR   65000           5
4       5   John            AI   58000           1
5       6   Aman            HR   62000           4
6       7  Priya  Data Science   54000           3

In [114]:
data.columns

Index(['emp_id', 'name', 'department', 'salary', 'experience'], dtype='str')

In [115]:


# Create Dataset
data = {
    "Name": ["Amit", "Shan", "Ravi", "Amit", "Shan", "Ravi"],
    "Department": ["IT", "HR", "IT", "HR", "IT", "HR"],
    "Salary": [50000, 60000, 55000, 52000, 62000, 58000],
    "Experience": [2, 4, 3, 2, 5, 4]
}

df = pd.DataFrame(data)

print("Original Dataset:\n")
print(df)

# 1. Total Salary by Department
print("\nTotal Salary by Department:")
print(df.groupby("Department")["Salary"].sum())

# 2. Average Salary by Department
print("\nAverage Salary by Department:")
print(df.groupby("Department")["Salary"].mean())

# 3. Multiple Aggregations
print("\nMultiple Aggregations:")
print(df.groupby("Department").agg({
    "Salary": ["sum", "mean", "max"],
    "Experience": "mean"
}))

# 4. Group by Multiple Columns
print("\nSalary by Department and Name:")
print(df.groupby(["Department", "Name"])["Salary"].sum())

# 5. Count Employees in Each Department
print("\nEmployee Count by Department:")
print(df.groupby("Department")["Name"].count())

Original Dataset:

   Name Department  Salary  Experience
0  Amit         IT   50000           2
1  Shan         HR   60000           4
2  Ravi         IT   55000           3
3  Amit         HR   52000           2
4  Shan         IT   62000           5
5  Ravi         HR   58000           4

Total Salary by Department:
Department
HR    170000
IT    167000
Name: Salary, dtype: int64

Average Salary by Department:
Department
HR    56666.666667
IT    55666.666667
Name: Salary, dtype: float64

Multiple Aggregations:
            Salary                      Experience
               sum          mean    max       mean
Department
HR          170000  56666.666667  60000   3.333333
IT          167000  55666.666667  62000   3.333333

Salary by Department and Name:
Department  Name
HR          Amit    52000
            Ravi    58000
            Shan    60000
IT          Amit    50000
            Ravi    55000
            Shan    62000
Name: Salary, dtype: int64

Employee Count by Department:
Department
HR    3
IT    3
Name: Name, dtype: int64

In [116]:
import pandas as pd

data = {
    "Department": ["AI", "IT", "AI", "HR"],
    "Salary": [50000, 60000, 55000, 52000]
}

df = pd.DataFrame(data)

x = df.groupby("Department")

print(x.get_group("AI"))

  Department  Salary
0         AI   50000
2         AI   55000

In [118]:
import pandas as pd

# Create Dataset
data = {
    "Department": ["AI", "IT", "AI", "HR", "IT", "AI", "HR"],
    "Salary": [50000, 60000, 55000, 52000, 60000, 50000, 52000],
    "Experience": [2, 4, 3, 2, 5, 2, 2]
}

df = pd.DataFrame(data)

print("Original Data:\n")
print(df)

# 1️⃣ Mean Salary by Department
print("\nMean Salary by Department:")
print(df.groupby("Department").mean())

# 2️⃣ Count of Employees by Department
print("\nCount of Employees by Department:")
print(df.groupby("Department")["Salary"].count())

# 3️⃣ Mode Salary by Department
print("\nMode Salary by Department:")
print(df.groupby("Department")["Salary"].agg(lambda x: x.mode()[0]))

Original Data:

  Department  Salary  Experience
0         AI   50000           2
1         IT   60000           4
2         AI   55000           3
3         HR   52000           2
4         IT   60000           5
5         AI   50000           2
6         HR   52000           2

Mean Salary by Department:
                  Salary  Experience
Department
AI          51666.666667    2.333333
HR          52000.000000    2.000000
IT          60000.000000    4.500000

Count of Employees by Department:
Department
AI    3
HR    2
IT    2
Name: Salary, dtype: int64

Mode Salary by Department:
Department
AI    50000
HR    52000
IT    60000
Name: Salary, dtype: int64

# marge  - (column bases ) like sql jion 
inner outer right left

In [1]:
import pandas as pd

students = pd.DataFrame({
    "student_id": [1, 2, 3, 4],
    "name": ["Ali", "Rahul", "Aman", "Sara"]
})

marks = pd.DataFrame({
    "student_id": [1, 2, 4, 5],
    "marks": [85, 90, 78, 88]
})

print(students)
print(marks)

   student_id   name
0           1    Ali
1           2  Rahul
2           3   Aman
3           4   Sara
   student_id  marks
0           1     85
1           2     90
2           4     78
3           5     88

In [ ]:
pd.merge(students,marks)

   student_id   name  marks
0           1    Ali     85
1           2  Rahul     90
2           4   Sara     78

In [6]:
pd.merge(students,marks, on="student_id", how="inner")

   student_id   name  marks
0           1    Ali     85
1           2  Rahul     90
2           4   Sara     78

In [7]:
pd.merge(students,marks, on="student_id", how="outer")

   student_id   name  marks
0           1    Ali   85.0
1           2  Rahul   90.0
2           3   Aman    NaN
3           4   Sara   78.0
4           5    NaN   88.0

## join - (which is index base)

In [8]:
employees = pd.DataFrame({
    "emp_id": [101, 102, 103, 104],
    "name": ["Amit", "Neha", "Ravi", "Pooja"]
}).set_index("emp_id")

departments = pd.DataFrame({
    "emp_id": [101, 102, 105],
    "department": ["IT", "HR", "Finance"]
}).set_index("emp_id")

print(employees)
print(departments)

         name
emp_id
101      Amit
102      Neha
103      Ravi
104     Pooja
       department
emp_id
101            IT
102            HR
105       Finance

In [9]:
employees.join(departments)

         name department
emp_id
101      Amit         IT
102      Neha         HR
103      Ravi        NaN
104     Pooja        NaN

In [11]:

employees.join(departments, how="inner")
# employees.join(departments, how="outer")

        name department
emp_id
101     Amit         IT
102     Neha         HR